### ISSUE TITLE
How to color layers according to published cluster labels?

### ISSUE THREAD

**Issue by Yuhang-King** [raphael-group/paste#1]
![image](https://user-images.githubusercontent.com/44969387/112295253-b1425c80-8cce-11eb-8042-172b3b757e77.png)

How to color layers according to published cluster labels?

And I just can get this:

![image](https://user-images.githubusercontent.com/44969387/112297973-77bf2080-8cd1-11eb-9347-2f308fc7e7d3.png)

**Comment by RonZeira** [comment]
You should change the color of each spot in the 3d plot according to its cluster assignment and not its layer assignment. Specifically, you can create a dataframe where each spot is an entry has x,y,z coordinates and cluster assignment and then plot this dataframe in 3d using 'px.scatter_3d' as done is the tutorial.
