### ISSUE TITLE
Is there any way to increase the running speed? 

### ISSUE THREAD

**Issue by Yao-14** [raphael-group/paste#12]
Hello, I am very interested in your package, and I also tried to use pairwise alignment. But when the data I input is slightly larger, the running speed will be very slow, and it may take a day. Is there any way to increase the running speed?

**Comment by xiangrong7** [comment]
I have met this question too.......

**Comment by RonZeira** [comment]
Thanks for your interest in our method and for pointing out this issue. We are working on improving on improving the runtime. In the meanwhile, I suggest you give the method an initial alignment to speedup the convergence. You can give it using the Python interface or the command line interface. By default, the optimization starts with a uniform alignment.

**Comment by xiangrong7** [comment]
> Thanks for your interest in our method and for pointing out this issue. We are working on improving on improving the runtime. In the meanwhile, I suggest you give the method an initial alignment to speedup the convergence. You can give it using the Python interface or the command line interface. By default, the optimization starts with a uniform alignment.

Thank you for your reply. Great tool!

**Comment by mrland99** [comment]
Our new recent version supports GPU implementation which should help speed up run time.
