### ISSUE TITLE
How to get the gene expression matrix of the center object for the subsequent cluster analysis?

### ISSUE THREAD

**Issue by hzongyao** [raphael-group/paste#17]
How to get the gene expression matrix of the center object for the subsequent cluster analysis? Thank you ！

**Comment by mrland99** [comment]
The center align method should return a `center_slice`.  The gene expression matrix is then stored in `center_slice.X` and the low dimensional representation in `center_slice.uns['paste_W']` and `center_slice.uns['paste_H']`.
