### ISSUE TITLE
How to understand the meaning of mapping value in the result file？

### ISSUE THREAD

**Issue by hzongyao** [raphael-group/paste#18]
How to understand the meaning of mapping value in the result file（files containing a mapping of spots between the center slice (rows) to each input slice (cols)）? Does the smaller the value mean the better the mapping effect ? Thank you ！

**Comment by mrland99** [comment]
For a given slice, each spot is assigned a value such that the sum of all spots sum to 1. The default is uniform, so each spot gets weight $1/n$. Next, PASTE calculates a mapping between a spot on one slice to spots on another. Essentially, we take the $1/n$ and assign it to the spots it maps. Note that spots can map one to one, or our $1/n$ can be broken up and mapped to multiple spots. The higher the value, the "better" the mapping.
