### ISSUE TITLE
What does this mean when running a program that generates？

### ISSUE THREAD

**Issue by hzongyao** [raphael-group/paste#19]
Max number of iteration reached, currently 100000. Sometimes iterations go on in cycle even though the solution has been reached, to check if it's the case here have a look at the minimal reduced cost. If it is very close to machine
precision, you might actually have the correct solution, if not try setting the maximum number of iterations a bit higher
/home/user/anaconda3/envs/bio3/lib/python3.7/site-packages/ot/lp/__init__.py:343: UserWarning: numItermax reached before optimality. Try to increase numItermax.

**Comment by mrland99** [comment]
It appears this warning is thrown by POT package itself. The basic idea is that sometimes their solver doesn't converge perfectly all the time, so to avoid infinite run time the set a max number of iterations. From my experience, the default should be fine and doesn't affect results too much.
