### ISSUE TITLE
Issue on loading slices

### ISSUE THREAD

**Issue by CHAOYiming** [raphael-group/paste#20]
Dear PASTE community, 

Thanks for designing this amazing tool!

I am currently trying to align two 10x visium slice together. However, I got this error when doing pairwise alignment: `InvalidIndexError: Reindexing only valid with uniquely valued Index objects`. I also found that I cannot plot the spatial plots with scanpy or plot function. I checked that I have six columns in `slice3.obsm['spatial']`, while it should be two according to tutorial. When I tried to drop some columns I got following error: `Value passed for key 'spatial' is of incorrect shape. Values of obsm must match dimensions (0,) of parent. Value had shape (4448, 6) while it should have had (4449,).`

I guess there is some problem of my two input csv file? For the spatial coordinate I directly use the `tissue_positions_list.csv` in spaceranger output folder. For the count matrix, my processing are as followed: 
> adata = sc.read_visium("/usersdata/yiming/VIO/spaceranger_run/D1/outs", count_file="raw_feature_bc_matrix.h5",  load_images="tissue_hires_image.png", source_image_path="/usersdata/yiming/VIO/spaceranger_run/D1/outs/spatial")
slice4=adata.X.toarray()
pd.DataFrame(data=slice4, index=adata.obs_names, columns=adata.var_names).to_csv('/home/yiming/vio_analysis/ST/paste_slices/slice4.csv')

Would like to know if there is any problem of my input data and how to solve this issue. Thank you so much!!

Best,
Yiming

**Comment by mrland99** [comment]
The spatial column should only have two columns representing the `x` and `y` coordinates for each spot. 

What are the 6 column in your spatial data? It is possible you need to subset for only the `x` and `y` columns, if they are there.

**Comment by CHAOYiming** [comment]
Hi. Sorry for late reply. 

I checked the spaceranger documentation (https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/images). The six columns are: `barcode, in_tissue, array_row, array_col, pxl_row_in_fullres, pxl_col_in_fullres`. So i subset the `array_row, array_col` as coordinate. However i still got the error when running `pst.pairwise_align`: 
> InvalidIndexError: Reindexing only valid with uniquely valued Index objects

I found your example coor.csv has ~200 rows but mine is ~4k rows. Is this the problem? 
Thank you so much for the help!

Best,
Yiming

**Comment by mrland99** [comment]
Do you know which line is `pst.pairwise_align()` is causing that error? It seems like an error within pandas. 

Also try storing the coordinates as a 2d numpy array in `.obsm['spatial']`.

The number of rows should be the same as the number of spots, as the `i`-th coordinate should correspond to the `i`-th spot. So as long as that aligns, you should be fine with 4k rows.

**Comment by CHAOYiming** [comment]
Hi, thanks for your suggestions. 
I use adata.obsm['spatial'] as the coordinate. My scripts on preparing two csv file are as followed: 

> ### take out GEX and coord
> adata = sc.read_visium("/usersdata/yiming/VIO/spaceranger_run/D1/outs", count_file="raw_feature_bc_matrix.h5", load_images="tissue_hires_image.png", source_image_path="/usersdata/yiming/VIO/spaceranger_run/D1/outs/spatial")
> adata.to_df().to_csv('/home/yiming/vio_analysis/ST/paste_slices/slice4.csv')
> np.savetxt("/home/yiming/vio_analysis/ST/paste_slices/slice4_coor.csv", adata.obsm['spatial'], delimiter=",")

The data loading step is fine. However I still got the same error when doing pairwise alignment: 

> InvalidIndexError                         Traceback (most recent call last)
> /tmp/ipykernel_111284/1020119981.py in <module>
> ----> 1 pi34 = pst.pairwise_align(slice3, slice4)
> 
> ~/.conda/envs/velocyte/lib/python3.7/site-packages/paste/PASTE.py in pairwise_align(sliceA, sliceB, alpha, dissimilarity, use_rep, G_init, a_distribution, b_distribution, norm, numItermax, backend, use_gpu, return_obj, verbose, gpu_verbose, **kwargs)
>      75     # subset for common genes
>      76     common_genes = intersect(sliceA.var.index, sliceB.var.index)
> ---> 77     sliceA = sliceA[:, common_genes]
>      78     sliceB = sliceB[:, common_genes]
>      79 
> 
> ~/.conda/envs/velocyte/lib/python3.7/site-packages/anndata/_core/anndata.py in __getitem__(self, index)
>    1111     def __getitem__(self, index: Index) -> "AnnData":
>    1112         """Returns a sliced view of the object."""
> -> 1113         oidx, vidx = self._normalize_indices(index)
>    1114         return AnnData(self, oidx=oidx, vidx=vidx, asview=True)
>    1115 
> 
> ~/.conda/envs/velocyte/lib/python3.7/site-packages/anndata/_core/anndata.py in _normalize_indices(self, index)
>    1092 
>    1093     def _normalize_indices(self, index: Optional[Index]) -> Tuple[slice, slice]:
> -> 1094         return _normalize_indices(index, self.obs_names, self.var_names)
>    1095 
>    1096     # TODO: this is not quite complete...
> 
> ~/.conda/envs/velocyte/lib/python3.7/site-packages/anndata/_core/index.py in _normalize_indices(index, names0, names1)
>      34     ax0, ax1 = unpack_index(index)
>      35     ax0 = _normalize_index(ax0, names0)
> ---> 36     ax1 = _normalize_index(ax1, names1)
>      37     return ax0, ax1
>      38 
> 
> ~/.conda/envs/velocyte/lib/python3.7/site-packages/anndata/_core/index.py in _normalize_index(indexer, index)
>      96             return positions  # np.ndarray[int]
>      97         else:  # indexer should be string array
> ---> 98             positions = index.get_indexer(indexer)
>      99             if np.any(positions < 0):
>     100                 not_found = indexer[positions < 0]
> 
> ~/.conda/envs/velocyte/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_indexer(self, target, method, limit, tolerance)
>    3440 
>    3441         if not self._index_as_unique:
> -> 3442             raise InvalidIndexError(self._requires_unique_msg)
>    3443 
>    3444         if not self._should_compare(target) and not is_interval_dtype(self.dtype):
> 
> InvalidIndexError: Reindexing only valid with uniquely valued Index objects

When i tried to plot the spatial slice, it was all empty. `sc.pl.spatial(slice4, color = "n_counts", spot_size = 1) ` So I guess there is something wrong with my coordinates. 

Again thanks for your help!

Best,
Yiming

**Comment by mrland99** [comment]
Hmm it looks like the error occurs when PASTE tries to subset the adata object by common genes.

Can you check if adata.var_names have any duplicate genes? I think that what might be causing the error. If so you need to combine them or rename them or something.

**Comment by CHAOYiming** [comment]
Thanks Max. 
I added one more line to make var.names unique `adata.var_names_make_unique()`. Now the pairwise alignment step works!!
However i guess there is still something wrong with the spatial coordinate. As mentioned, `sc.pl.spatial(slice4, color = "n_counts", spot_size = 1)` is still empty, and `pst.plot_slice(slice4, ['#4daf4a'])` gives a messy image that is not likely the original image. But the coordinate saving step looks fine right? `np.savetxt("/home/yiming/vio_analysis/ST/paste_slices/slice4_coor.csv", adata.obsm['spatial'], delimiter=",")`

Thanks,
Yiming

**Comment by mrland99** [comment]
It's hard for me to know what's going on with your spatial coordinates. Does running pairwise align change the values of your spatial coordinates (it shouldn't)? Does the plot before running PASTE look correct?

**Comment by CHAOYiming** [comment]
Hi Max, the plot looks bad after i load the slides. 
Anyway thanks for your kind help! I will close this issue.
