### ISSUE TITLE
pairwise alignement on H&E images

### ISSUE THREAD

**Issue by sophieRAIBAUD** [raphael-group/paste#23]
Hello
I am working with spatial transcriptomic data and would like to align data from several slices.
It's working very well on spatial data but now I would like to align the H&E images using the same alignement matrice 
Would it be possible ?
many thanks !
Sophie

![image](https://user-images.githubusercontent.com/17746001/181242380-87796cca-52f1-46e6-ae28-a4b3c432827f.png)

**Comment by mrland99** [comment]
Hi Sophie,

PASTE currently doesn't support rotating and translating H&E images, but we can look into adding it now that you mention it. 

A possible solution in the meantime would be to get the angle of rotation and translation for each slice during the alignment step and then apply them yourself to your H&E image accordingly. 

You can get the angles and translations by setting `stack_slices_pairwise(output_params = True)` and `stack_slices_center(output_params = True)`.

Setting parameter `matrix = True` will also return the rotation matrix instead of the angle if you prefer that.

Let me know if that makes sense.

Best,
Max

**Comment by sophieRAIBAUD** [comment]
Many thank,
I ll try it

**Comment by sophieRAIBAUD** [comment]
dear Max,
I have tried but the image in squidpy is in 3 dimensions instead of 2 as the spatial coordinates;
I guess this are the 3 rgb codes but I dont find the real coordinates :(
![image](https://user-images.githubusercontent.com/17746001/187386747-96e3ab94-cf1e-4ca5-b471-2b4ff4e94044.png)
Many thanks 
Sophie

**Comment by sophieRAIBAUD** [comment]
Dear Max,
I managed to rotate the data according to the output 

![image](https://user-images.githubusercontent.com/17746001/187725772-6e7bd466-bdbb-49f1-a447-3d82ea805f7c.png)

-1.3087651035520074*57.3: angle in degres

test4 = scipy.ndimage.rotate(test3, -1.3087651035520074*57.3, axes=(1, 0), 
                     reshape=True, output=None, order=3, mode='constant', cval=0.0, prefilter=True)

![image](https://user-images.githubusercontent.com/17746001/187726115-b7be5a86-a23a-4af8-8ee2-792430de403f.png)

but I dont understand how to tranlate it with this information :
[array([6076.08448276, 6387.14137931]),
  array([4531.87719298, 6203.64912281])])

could you help me ?
Many many thanks !
Sophie

**Comment by mrland99** [comment]
Hi Sophie,

I believe you can translate the image using OpenCV python library: https://pyimagesearch.com/2021/02/03/opencv-image-translation/

The code to translate your image would probably look something along these lines:

```
import cv2

# get your image (can also supply rotated image)
image = adata.uns['spatial']['V1_Human_Lymph_Node']['images']['lowres']

# translate by t_x, t_y which you get from `stack_slices_pairwise()`
t_x = 25
t_y = 500
M = np.float32([
    [1, 0, t_x],
    [0, 1, t_y]
])
shifted = cv2.warpAffine(image, M, (image.shape[1], image.shape[0]))

# update your adata image to the new shifted image
adata.uns['spatial']['V1_Human_Lymph_Node']['images']['lowres'] = shifted
```

This should allow you to translate your image.

**Comment by sophieRAIBAUD** [comment]
OK thanks !
here what I get with 25, 500 translation 
![image](https://user-images.githubusercontent.com/17746001/187869379-a9a08133-7c50-435e-b2bb-7efc7b1c48b9.png)

but now I do,nt know how to use the matrix:
[-1.3087651035520074]  => angle OK

 [array([6076.08448276, 6387.14137931]),
  array([4531.87719298, 6203.64912281])])
=> ??

6076.08448276 is to high, so I tried the difference 
but still dont get the perferct alignement

Many thanks !!

**Comment by mrland99** [comment]
Hi Sophie,

```
[array([6076.08448276, 6387.14137931]),
array([4531.87719298, 6203.64912281])])
```
Should be the translation amount (`t_x, t_y`) for each of the two slices. The reason why the number is so high is I believe that the spatial coordinates are scaled up from the image coordinates.

You should be able to find the scale factors for the image in your adata using something along the lines of: 
`adata.uns['spatial']['V1_Human_Lymph_Node']['scalefactors']`

which outputs
```
{'spot_diameter_fullres': 89.48996643177776,
 'tissue_hires_scalef': 0.17011142,
 'fiducial_diameter_fullres': 144.56071500517945,
 'tissue_lowres_scalef': 0.051033426}
```
You can then use this to scale down the transformation according to the scalefactor and then using the scaled down `t_x, t_y` you should be able to align the image.

Best,
Max

**Comment by sophieRAIBAUD** [comment]
I found the solution back to spaceranger, turn the image and run the count again
