### ISSUE TITLE
Issues with spatial initial mapping

### ISSUE THREAD

**Issue by Nuwaisir-1998** [raphael-group/paste#24]
In supplementary section 1.3, you have noted that you found that a heuristic for initializing the OT solver based on an alignment found using only the spatial coordinates improves the performance of PASTE for some datasets. In this heuristic, you solve an optimization problem that seeks to find a rotation of the spatial coordinates in one slice that minimizes the Wasserstein OT between the spots of the two slices where the distance is measured according to the spatial distances between the spots.

But your implementation of [match_spots_using_spatial_heuristic](https://github.com/raphael-group/paste/blob/main/src/paste/helper.py#:~:text=match_spots_using_spatial_heuristic) function takes the spatial coordinates of the two slices, centers them, calculates the pairwise distances between the spots of the two slices, and then solves the Wasserstein OT using `ot.emd`. Sorry if I am missing any detail here but I was not able to follow how your implementation finds an appropriate rotation. It just solves the OT based on the given spatial coordinates of the two slices. I've run Paste by rotating one of the given two slices (say 151673, and 151674 samples of the DLPFC) by multiple angles, and the initial mapping based on only the spatial coordinates was not finding the appropriate rotation.
![image](https://user-images.githubusercontent.com/57160333/186718771-764a2704-7a8c-4de4-8221-28ca8068b335.png)
Here, I've rotated the 151673 sample of DLPFC (left side) by 90 degrees. You can see that the final mapping of Paste is not what is expected (as Paste is considered to be rotation invariant) when the initialization of the OT solver is based on the spatial alignment heuristic and the value of alpha is `0.1`.
However, for this case, I was able to make the final alignment better by changing the value of alpha to `0.001` giving higher priority to gene expression difference of the spots than the spatial coordinates. The alignment looked like the following:
![image](https://user-images.githubusercontent.com/57160333/186738911-ddc79e89-e83a-4077-b077-4b9eb2e88caa.png)

But for the case of mapping between DLPFC samples 151670 and 151671, similar problems remain at alpha = `0.1`.
![image](https://user-images.githubusercontent.com/57160333/186739121-414355f4-5b74-473a-95a5-3d82ac46b280.png)

The mapping is not properly fixed at alpha = `0.001`, it seems to be going towards a somewhat better solution at alpha = `0.0001`.
Here is the mapping when alpha = `0.0001`
![image](https://user-images.githubusercontent.com/57160333/186739181-a2222ec7-a936-4d22-99df-998405d1939e.png)

The link to the analyses: https://colab.research.google.com/drive/1nTsbY5nxgeYLXXS9E0xTGS5jpUeTjwTl?usp=sharing 

From the above discussion, it seems to me that, the current implementation of PASTE doesn't really remain rotation invariant of any of the slices when the OT solver is initialized based on an alignment found using only the spatial coordinates, as the implementation of the mentioned heuristic doesn't seem to find any rotation angle, even though in the supplementary section 1.3 it is said that the heuristic seeks to find a rotation of the spatial coordinates in one slice that minimizes the Wasserstein OT distance.

**Comment by mrland99** [comment]
Hi,

I'm so sorry for some reason I am just now seeing this-- I thought this was resolved.

I agree with your points and I just wanted to clarify something. When we say PASTE is rotation invariant, it is in the sense that PASTE utilizes pairwise distances between spots, which remains constant even upon rotation. Thus, you should expect the same result upon rotation.

Now, the reason we used the `match_spots_using_spatial_heuristic()` function to find an initial mapping, is that sometimes our OT solver can get stuck a local minima during convergence depending on the initialization. But I want to clarify that the function was intended to be more of an example on how to find an initialization. It doesn't always work as you've shown.

Intuitively, the more symmetric the shape of the tissue the harder it is to find the optimal rotation based solely spatial information. For example, if the spots between layers formed a perfect square and you were only looking at spatial coordinates, you'd have no idea which 90 degree rotation would give the optimal rotation. This is also why in the case above you see better results at lower alpha (giving more weight to gene expression). 

In situations like these, if you know the proper orientation (to some degree), I would recommend rotating the spatial coordinates yourself before running PASTE.

Let me know if that answers your question.
Max
