### ISSUE TITLE
Cluster labels in squamous cell carcinoma (SCC) ST dataset

### ISSUE THREAD

**Issue by vanhoan310** [raphael-group/paste#3]
I want to run PASTE on the SCC dataset. Unfortunately I could not find the cluster labels in the dataset from the original paper (Ji et al., Cell 2020). Would it be possible to obtain the dataset with the cluster labels?
Thanks!

**Comment by mrland99** [comment]
Yes, we have the cluster labels from the original paper in a separate file. I can send it. What is your email? I assume you have the count matrices downloaded and only need the cluster labels correct?

**Comment by vanhoan310** [comment]
Yes, I downloaded the count matrices from the GEO access provided in the paper. Could you please send the cluster labels to the email: vanhoan310@gmail.com. Thank you so much for your help.
