### ISSUE TITLE
Not able to run center_align due to an attribute error

### ISSUE THREAD

**Issue by KSimi7** [raphael-group/paste#31]
Hi, 

I tried running center_align with my slices and I got the following error. 

`AttributeError: module 'ot.gromov' has no attribute 'cg'`

The POT version I currently have is 0.9.0. There are other similar issues reported with the usage of ot.gromov but none of them mention an attribute cg. 

Does PASTE require a specific version of POT to work?

Thanks, 
Harsimran Kaur

**Comment by mrland99** [comment]
Hi,

Sorry for just now seeing this. Looking into this issue.

Best,
Max

**Comment by mrland99** [comment]
Hi,

It looks like POT did a big update to Gromov Wasserstein in the most recent version 0.9.0. Can you try reverting to an older POT version for now?

I will look into updating the code to be compatible with the newest version.

Thanks,
Max

**Comment by RubyLiu206** [comment]
Hi, I encountered the same issue, you can find the path of this package (for me it's under ....\Anaconda3\envs\st_env\Lib\site-packages\paste). Then, you can change that line from ot.gromov.cg to whatever POT method you want, ie. ot.gromov.sampled_gromov_wasserstein(...). It worked for me, and hope PASTE group can update the package later maybe

**Comment by mrland99** [comment]
Ah cool this is helpful thanks @RubyLiu206. I haven't had a chance to look into the newest changes to POT yet but it does seem like a quick fix. I will do it when I get a chance.

Thanks,
Max

**Comment by RubyLiu206** [comment]
> Ah cool this is helpful thanks @RubyLiu206. I haven't had a chance to look into the newest changes to POT yet but it does seem like a quick fix. I will do it when I get a chance.
> 
> Thanks, Max



Will one more issue came: fused_gromov_wasserstein2() got multiple values for argument 'C1' 
I think it because the inconsistency of PASTE and POT new version somehow. If continue work on changing PASTE developer code... might not work. 

Sorry to bring more problems haha

**Comment by RubyLiu206** [comment]
I found the easiest way to fix this issue is downgrade POT to 0.8.0. You don't need to change anything else.

**Comment by mrland99** [comment]
@RubyLiu206 which version of PASTE are you using that has fused_gromov_wasserstein2()?

EDIT: Oh I see-- I think changing to ot.optim.cg() fixes it.

**Comment by mrland99** [comment]
Just updated PASTE. The newest version should be compatible with POT v0.9.0.
