### ISSUE TITLE
TypeError: cg() got multiple values for argument 'numItermax'

### ISSUE THREAD

**Issue by Tako-liu** [raphael-group/paste#33]
Hello, great work!
 I encountered the following error when running the sample data, does anyone know what the problem is? 
I get an error when running this statement `pi12 = pst.pairwise_align(slice1, slice2)` 
The error message is:
`Using selected backend cpu. If you want to use gpu, set use_gpu = True.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [22], in <cell line: 1>()
----> 1 pi12 = pst.pairwise_align(slice1, slice2)

File ~/miniconda3/envs/st/lib/python3.8/site-packages/paste/PASTE.py:149, in pairwise_align(sliceA, sliceB, alpha, dissimilarity, use_rep, G_init, a_distribution, b_distribution, norm, numItermax, backend, use_gpu, return_obj, verbose, gpu_verbose, **kwargs)
    147         if use_gpu:
    148             G_init.cuda()
--> 149 pi, logw = my_fused_gromov_wasserstein(M, D_A, D_B, a, b, G_init = G_init, loss_fun='square_loss', alpha= alpha, log=True, numItermax=numItermax,verbose=verbose, use_gpu = use_gpu)
    150 pi = nx.to_numpy(pi)
    151 obj = nx.to_numpy(logw['fgw_dist'])

File ~/miniconda3/envs/st/lib/python3.8/site-packages/paste/PASTE.py:358, in my_fused_gromov_wasserstein(M, C1, C2, p, q, G_init, loss_fun, alpha, armijo, log, numItermax, tol_rel, tol_abs, use_gpu, **kwargs)
    355         return solve_gromov_linesearch(G, deltaG, cost_G, C1, C2, M=0., reg=1., nx=nx, **kwargs)
    357 if log:
--> 358     res, log = ot.optim.cg(p, q, (1 - alpha) * M, alpha, f, df, G0, line_search, log=True, numItermax=numItermax, stopThr=tol_rel, stopThr2=tol_abs, **kwargs)
    360     fgw_dist = log['loss'][-1]
    362     log['fgw_dist'] = fgw_dist

TypeError: cg() got multiple values for argument 'numItermax'`

**Comment by mrland99** [comment]
Hi,

What version of PASTE and POT are you using? I am unable to recreate the error. Are you using the newest version of PASTE?

Best,
Max

**Comment by Tako-liu** [comment]
Hi! Thank you for your suggestion. I successfully ran the sample file, so I started working with my spatial transcriptome data. Since I only have one data point, I wanted to try doubling it by overlaying it on itself. However, after aligning, the coordinates for PASTE alignment are a bit mixed up. Is there a way to resolve this? Are there any parameters that can be adjusted?
![image](https://github.com/raphael-group/paste/assets/44719257/ba66a031-d8c9-4d58-a1d5-fab4fc64e3ee)
![image](https://github.com/raphael-group/paste/assets/44719257/04a5523a-eddc-4f01-a29b-ebb6c28c5262)

**Comment by mrland99** [comment]
Hi, 

Sorry for the late response. When you doubled it by overlaying it on itself, did you change the copy at all? What are you trying to achieve by overlaying it on itself?

**Comment by Tako-liu** [comment]
I apologize for the delayed response. I was trying to stack two different chips from the same organization, but they had slight differences in their structures. However, when I stacked the two chips together, I observed an opposite outcome. So, I attempted to stack the data from the same chip onto itself, but I still encountered the same situation. I don't understand what is happening and if there is any way for me to control this situation.

**Comment by zhangms1709** [comment]
I get a similar issue when trying to run pairwise alignment. Is this an issue with the [OT](https://pythonot.github.io/gen_modules/ot.optim.html) package? I was able to fix it by getting rid of the line_search input into ot.optim.cg() because I took a look at the code for the function and line_search is no longer a parameter for that function so it was mistaking it for numItermax.

**Comment by mrland99** [comment]
Ah that sounds like it could be the issue. There was a similar issue a while ago when POT updated their package previously. It is likely that could be the case. What version of POT did you end up using in your fix?

**Comment by zhangms1709** [comment]
I was able to fix it using POT-0.9.3 (I restored line_search as one of the parameters and it worked fine), I got the issue originally with POT-0.8.1.
