### ISSUE TITLE
How to Understand the Superhigh Number of Median Genes

### ISSUE THREAD

**Issue by yuntwang** [raphael-group/paste#34]
Hi，Why is there such a high median number of genes when multiple slices are integrated into one slice.

Examples are as follows：

              X     Y leiden  n_genes
cell_241  15842  4731      0    15300
cell_261  15771  4995      1    15300
cell_253  15851  4913      1    15300
cell_260  15817  4978      1    15300
cell_264  15777  5063      7    15300
...         ...   ...    ...      ...
cell_493  16488  6993      0    15300
cell_495  16446  7049      1    15300
cell_491  16523  6940      0    15300
cell_494  16485  7030      1    15300
cell_496  16456  7087      4    15300

Looking forward to receiving a response from the author.
Thanks

**Comment by mrland99** [comment]
Let me know if I'm not understanding your question correctly.

It is important to recognize that PASTE doesn't do any additional filtering of genes aside from finding genes in common between slices. Thus, the high # of genes is just all genes in common between your slices-- in common being that they are in adata.var_names across all slices. It likely that many of those genes in a cell are actually uninformative (e.g. zero counts, not differentially expressed). 

One thing you can try is to actually filter the genes in your slices before running PASTE. Or you can filter for DEGs after running PASTE.

**Comment by yuntwang** [comment]
I get it
thanks
