### ISSUE TITLE
Inconsistent gene expression positions before and after integration

### ISSUE THREAD

**Issue by yuntwang** [raphael-group/paste#35]
Hi，I used software paste(paste.center_align) to integrate two identical slices，then, the expression of a certain gene before and after integration was plotted, and it was found that the expression position of this gene was inconsistent.

The above figure shows the result of a gene before integration, while the following figure shows the result of a gene after integration.

![before](https://github.com/raphael-group/paste/assets/27258713/00a3c30d-1474-4d6f-a4ea-c31b2cb7ae38)

![after](https://github.com/raphael-group/paste/assets/27258713/88837603-ea67-4ac3-bc0f-48c5648d69c0)

**Comment by mrland99** [comment]
When you say identical slices, how exactly are they identical. It looks like the gene expression is slightly different? And when you say inconsistent, what do you mean by that. What do you expect?

**Comment by yuntwang** [comment]
**identical slices means**: exactly the same without any differences, I'll take a slice and integrate it.
**inconsistent**：there is a significant difference in the expression position of a certain gene between the original section and the integrated section.

**Comment by mrland99** [comment]
So PASTE center align computes a Non-negative matrix factorization (NMF) which is why there should be a difference, although in this case it is surprising it is quite different. I'm not sure off the top of my head what could be causing this. Have you tried looking at the mapping between slices to see if it is consistent?

**Comment by yuntwang** [comment]
ok, I'll give it a try. 
Thank you.
