### ISSUE TITLE
Some questions about PAA metric

### ISSUE THREAD

**Issue by liuchunlei0430** [raphael-group/paste#37]
Thank you for making the excellent resource PASTE available to the public! We are hoping to use the metrics proposed in the PASTE method. However, we've encountered some uncertainties while using the code on GitHub.
 
1. In the paste_reproducibility/notebooks/stutil-analysis.ipynb, the method used for calculating pi(used for calculating pairwise alignment accuracy) uses the function  match_spots_using_spatial_heuristic. We noticed that this approach differs from the one implemented in pst.pairwise_align. Could you please clarify the differences, and which one is used to calculate pi for PAA metrics in the context of PASTE?
 
2. Could you kindly confirm that pi in the pst.pairwise_align function is based on the original slice or the aligned slice?
 
Thank you for your time and help.

**Comment by RonZeira** [comment]
1. The pst.pairwise_align function implements the PASTE OT formulation. The spatial heuristic is a fast heuristic based only on the spatial distances only and is an alternative when the slices are already almost spatially aligned. To summarize, You should use the pst.pairwise_align function.
2. pi_ij is the probability the a spot i in the first slice is aligned to the spot j in the second slice. This mapping is independent whether you apply a linear transformation to the slice coordinates.
