### ISSUE TITLE
command line tool works for pairwise alignment but crashes with -center

### ISSUE THREAD

**Issue by rosshandler** [raphael-group/paste#8]
Dear developers,

I find your tool very interesting. I am currently trying to align two replicates from a single cell spatial transcriptomics approach. I started by using the command line tool you provided and while the -pairwise option runs (with a warning: RESULT MIGHT BE INACURATE) the option -center crashes. I have filtered the matrices for non zero counts across both genes and cells. I ran the function as specified in your README file. Please find the error message below. Kindly could you let me know if you recognise this problem? Data is formatted as the sample data. And briefly, do you have any advice for the warning regarding the max number of iterations reached in the -pairwise option?

python paste-cmd-line.py -m center ...
Computing center alignment.
Filtered all slices for common genes. There are 97 common genes.
Traceback (most recent call last):
  File "/data1/ivanir/Ilaria2021/SpatialData/paste/paste-cmd-line.py", line 115, in <module>
    main(args)
  File "/data1/ivanir/Ilaria2021/SpatialData/paste/paste-cmd-line.py", line 82, in main
    center_slice, pis = center_align(initial_slice, slices, lmbda, args.alpha, args.n_components, args.threshold, dissimilarity=args.cost, distributions=[slices[i].obsm['weights'] for i in range(n_slices)], pis_init=pis_init)
  File "/data1/ivanir/Ilaria2021/SpatialData/paste/src/paste/PASTE.py", line 139, in center_align
    W = model.fit_transform(A.shape[0]*sum([lmbda[i]*np.dot(pis[i], to_dense_array(slices[i].X)) for i in range(len(slices))]))
  File "/data1/ivanir/Ilaria2021/SpatialData/paste/src/paste/PASTE.py", line 139, in <listcomp>
    W = model.fit_transform(A.shape[0]*sum([lmbda[i]*np.dot(pis[i], to_dense_array(slices[i].X)) for i in range(len(slices))]))
  File "<__array_function__ internals>", line 5, in dot
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

Many thanks,
Ivan

**Comment by RonZeira** [comment]
I think I found the bug that causes this crash and fixed it. Please check if the problem persists in the new version.
